### ISSUE TITLE
Massive fps drops after a while

### ISSUE THREAD

**Issue by Jadax** [AStupidRat/RatPoison#11]
Worked fine 1 game, but then after that it has lagged in every game after a few mins each time. Restarted game/java several times to test.

**Comment by AStupidRat** [comment]
Create a cfg, copy+paste the contents to a pastebin and link it here.

**Comment by Sawuus** [comment]
I have a problem with bunnyhop. CPU usage rises to 100%, at this time Bunnyhop does not work or works very slow. After a while throws an exception and everything returns to normal.

https://pastebin.com/S6amfJkE

**Comment by bitchtracker** [comment]
i have the same Problem with the fps Drops. cant seem to fix it. 
https://pastebin.com/ZxXtj01q

**Comment by AStupidRat** [comment]
@Sawuus Does this happen no matter what? Such as just starting the application and (trying to) bhop? I can't seem to replicate it, and did the error occur while saving/loading a cfg/default settings?

@Jadax @bitchtracker Are the fps drops related to saving? Immediately after launching poison? 
@Jadax Since it was fine one game, I suggest restarting your computer to see if that helps for now.

I'm pushing an update that should hopefully fix some of these issues, please lmk if they do or not.

**Comment by Sawuus** [comment]
This happens rarely at a random moment.

**Comment by themaluxis** [comment]
Didn't get any problem since last update (2h ago)
wait and see

**Comment by bitchtracker** [comment]
Okay will test the new update out. I will respond if there is any other Problem. thanks anyway for the great cheat!

**Comment by bitchtracker** [comment]
okay well i still got fps Drops and ist a pain in the ass to Play with it. i get a massive fps drop when i shoot an enemy.. ist the same cfg from before. 
and yes the fps Drops immediatly start when i go into a normal game. 
in like the Workshop map aim botz it work everything fine.

**Comment by themaluxis** [comment]
no problem for me in mm

https://pastebin.com/cbLxu4Bs

**Comment by AStupidRat** [comment]
@bitchtracker Im assuming your pc specs arent that great, for the drops in aim try increasing the AIM_DURATION in General.kts

**Comment by bitchtracker** [comment]
okay so i tested the other Version out and it works perfectly fine :d thanks!

**Comment by AStupidRat** [comment]
@bitchtracker Good to know, thanks for the info and input
