### ISSUE TITLE
Other Issues on 1.2.5

### ISSUE THREAD

**Issue by TheTreeThatGrows** [AStupidRat/RatPoison#9]
Saving and loading settings gives error.
I have visual settings disabled, but for some reason it automatically turns on after a while.
Aimbot and trigger bot sometimes stops working when using a new weapon.

**Comment by AStupidRat** [comment]
I just tested saving and loading cfgs, as well as saving to default and it work's fine for me. Are you using the latest build? If not provide the error that shows up.

**Comment by AStupidRat** [comment]
Saving & loading should be fixed, settings returning to default after awhile should be fixed in the latest push. I couldn't replicate aim/trig not working after awhile. If you have any other information for it such as when it happens (an estimate such as 20 minutes after launching), does it only happen with certain weapons (or all newly equipped ones like you said), and does waiting a couple seconds while holding the weapon fix it? Lmk if the update fixed some of the problems and any more issues you have.

**Comment by TheTreeThatGrows** [comment]
Found some new issues on the new patch update:
- Sometimes crashes the game when turning off visuals
- M4A4 RCS sometimes doesn't work when the aimbot locks on to a target (by holding aim key), and also sometimes crashes the hack when trying to configure it under individual weapon
- Still has some random FPS drops
- Aimbot (holding aim key) sometimes shakes and targets between head to body when using pistols. 

Other than that, most problems seems to be fixed :)

**Comment by AStupidRat** [comment]
Latest update should hopefully fix the visuals crashing, but I couldn't replicate the m4a4 or pistol aim problems, do these issues occur with the default settings?

**Comment by TheTreeThatGrows** [comment]
yes, it happens when i hold down a hotkey to aim/lock on a target. Once firing, the RCS sometimes doesnt work on the M4A4

**Comment by AStupidRat** [comment]
Again I can't replicate any problems with it on the latest build, when you say RCS, do you mean having RCS enabled, or the weapons natrual rcs when helping you aim? How often does it not work? Is it map/gamemode specific (such it happens in comp but not in deathmatch/aim botz)?
